version: '3.8'

services:
  camera-viewer:
    build: .
    ports:
      - "8080:8080"
    environment:
      # AWS Configuration
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      
      # Authentication
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      
      # Application Configuration
      - PORT=8080
    
    # Uncomment if you want to use AWS credentials from host
    # volumes:
    #   - ~/.aws:/root/.aws:ro
    
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/list-years"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s