name: Deploy to Server

on:
  push:
    branches: [main] # Adjust branch name as needed
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t camera-viewer:${{ github.sha }} .
          docker tag camera-viewer:${{ github.sha }} camera-viewer:latest

      - name: Save Docker image
        run: |
          docker save camera-viewer:latest | gzip > camera-viewer.tar.gz

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "camera-viewer.tar.gz,docker-compose.yml,Makefile,deploy.sh,nginx.conf,init-letsencrypt.sh"
          target: "/root/camera-viewer"
          strip_components: 0

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/camera-viewer

            # Load the new Docker image
            docker load < camera-viewer.tar.gz

            # Stop existing containers
            docker-compose down || true

            # Start with new image
            docker-compose up -d

            # Clean up
            rm camera-viewer.tar.gz
            docker image prune -f

            # Wait for service to start
            echo "Waiting for service to start..."
            sleep 3

            # Health check with retries (check via nginx proxy)
            for i in {1..5}; do
              echo "Health check attempt $i/5..."
              if curl -f -s http://localhost/health >/dev/null 2>&1; then
                echo "✅ Service is healthy!"
                break
              elif [ $i -eq 5 ]; then
                echo "❌ Health check failed after 5 attempts"
                docker-compose logs --tail=20
                exit 1
              else
                echo "Service not ready yet, waiting 10 seconds..."
                sleep 10
              fi
            done

            echo "Deployment completed successfully!"
